store/products/urls.py
from django.urls import path
from .views import IndexView, ProductsListView, test, basket_add, basket_remove

app_name = "products"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("category/<int:category_id>/", ProductsListView.as_view(), name="category"),
    path("page/<int:page>/", ProductsListView.as_view(), name="paginator"),
    path("basket/add/<int:product_id>/", basket_add, name="basket_add"),
    path("basket/remove/<int:basket_id>/", basket_remove, name="basket_remove"),
    path("test/", test, name="test"),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

store/users/urls.py
from django.urls import path
from .views import login, registration, profile, logout


app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
]

store/products/models.py
from django.db import models
from users.models import User
from django.db.models import Count, Sum

class Category(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to="products_images")
    description = models.TextField()
    short_description = models.CharField(max_length=64)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(
        Category, related_name="products", on_delete=models.CASCADE
    )

    def __str__(self):
        return f"Товар: {self.name} | Категория: {self.category}"
    
    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Basket(models.Model):
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="baskets"
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="baskets"
    )

    def __str__(self):
        return f"Корзина для {self.user} | Продукт: {self.product}"
    
    @classmethod
    def sum(cls):
        return cls.quantity * cls.product.price

store/products/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render, HttpResponseRedirect
from .models import Product, Category, Basket
from users.models import User
from django.db.models import F
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from store.settings import PER_PAGE
from django.views.generic import TemplateView, ListView
from .mixins import TitleMixin


class IndexView(TitleMixin, TemplateView):
    template_name = 'products/index.html'
    title = 'Главная страница'

class ProductsListView(TitleMixin, ListView):
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'
    paginate_by = 3
    title = 'Каталог'

    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context
    
    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.kwargs.get('category_id')
        if category_id:
            return queryset.filter(category_id=category_id)
        else:
            return queryset


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(product=product, user=request.user)
    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity = F("quantity") + 1
        basket.save()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])

def test(request):
    template = "products/test.html"
    return render(request, template)

store/products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> {{title}} </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    {% block css %}
    {% endblock css %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url "products:index" %}">Chic Boutique</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "products:products_list" %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url "users:profile" user.id%}">Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
                        {% if user.is_superuser %}
                            <li><a class="dropdown-item" href="{% url "admin:index" %}">Админ-панель</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url "users:logout" %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "users:login" %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}{% endblock content %}
{% block footer %}{% endblock footer %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

store/products/templates/products/basket.html
{% if basket %}
<h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
    Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
</h4>
{% for b in basket %}
<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title"> {{ b.product.name }} </h5>
        <p class="card-text">{{ b.product.description }}</p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item bg-light">
            <div class="row text-center">
                <div class="col-lg-4">
                    <input name="basketID" type="number" class="form-control"
                        value={{ b.quantity }} min="0">
                </div>
                <div class="col-lg-4"> {{ b.product.price }} </div>
                <div class="col-lg-4">
                    <a href="{% url "products:basket_remove" b.id %}">
                        <i class="fas fa-trash"></i>
                    </a>
                </div>
            </div>
        </li>
    </ul>
</div>
{% endfor %}
<div class="card mb-3">
    <div class="card-footer">
        <p class="float-left">Итого</p>
        <h4 class="float-right">{{ total_sum }} руб. </h4>
    </div>
</div>
<a class="btn btn-success btn-lg float-right" href="../orders/order-create.html">
    Оформить заказ
</a>
{% else %}
<h4 class="mt-3 mb-3 | text-center">
    В корзине ничего нет <span class="badge badge-secondary badge-pill"></span>
</h4>
{% endif %}

store/products/templates/products/index.html
{% extends "products/base.html" %}
{% load static %}
{% block css %}
<link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5" style="color: #23364e">Chic Boutique</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру!
                    Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url "products:products_list" %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

store/products/templates/products/products.html
{% extends "products/base.html" %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                {% for category in categories %}
                <a href="{% url "products:category" category.id  %}" class="list-group-item">{{ category }}</a>
                {% endfor %}
            </div>

        </div>

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src="{{ product.image.url }}"
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{ product.name }}</a>
                            </h4>
                            <h5>{{ product.price }} руб.</h5>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-outline-success" href={% url "products:basket_add" product.id %}>
                                Отправить в корзину
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% if is_paginated %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link" href="{% if page_obj.has_previous %} {% url "products:paginator" page_obj.previous_page_number %} {% else %} # {% endif %}" tabindex="-1" aria-disabled="true">Предыдущая</a>
                    </li>
                    {% for page in paginator.page_range %}
                        <li class="page-item">
                            <a class="page-link" href="{% url "products:paginator" page %}">
                                {{ page }}
                            </a>
                        </li>
                    
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link" href="{% if page_obj.has_next %} {% url "products:paginator" page_obj.next_page_number %} {% else %} # {% endif %}">Следующая</a>
                    </li>
                </ul>
            </nav>
            {% endif %}

        </div>

    </div>

</div>
{% endblock content %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2023</p>
    </div>
</footer>
{% endblock footer %}

store/products/templates/products/test.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="Вселенная настолько велика, Морти, что ничего на свете не имеет значения!">
        <title>Wubba Lubba Dub Dub</title>
        <link rel="icon" href="fav.ico" type="image">
        <style>    
            body {
              background:  #e2ba16;
            }
            h1 {color:#4035bd; text-align:center; font-size:40px}
          </style>
    </head>

    <body>
        <header>
              <ul>
                <li style="display: inline-block; font-size: 30px; font-family: sans-serif;">
                  <a href="http://127.0.0.1:8000/test/" style="color: #4035bd;">Главная страница</a>
                </li>
                <li style="display: inline-block; font-size: 30px; font-family: sans-serif;">
                  <a href="about/" style="color: #4035bd;">О сайте</a>
                </li>
              </ul>
            </nav>
          </header>
        <main>
            <hr>
            <div>
                <h1>Это сайт по Рику и Морти, Сученька!!</h1>
                <a style="color:#4035bd; text-align:center; font-size:25px" href="http://rik-i-morti.ru/"><h3>Тут можно посмотреть все новый серии!!</h3> </a>
            </div>
            <img src="https://upload.wikimedia.org/wikipedia/ru/thumb/7/70/Rick_and_Morty_Season_1.jpg/800px-Rick_and_Morty_Season_1.jpg" width="450" height="500">
            
            <div>
                <h2>
                <p style="color:#4035bd;">Тут вы можете найти<br>ссылки на все сезоны: </p>
                </h2>
                <h2>
                    <ul>
                        <li><a href="http://rik-i-morti.ru/sez-1/"> 1 СЕЗОН</a></li>
                        <li><a href="http://rik-i-morti.ru/sez-2/"> 2 СЕЗОН</a></li>
                        <li><a href="http://rik-i-morti.ru/sez-3/"> 3 СЕЗОН</a></li>
                        <li><a href="http://rik-i-morti.ru/sez-4/"> 4 СЕЗОН</a></li>
                        <li><a href="http://rik-i-morti.ru/sez-5/"> 5 СЕЗОН</a></li>
                        <li><a href="http://rik-i-morti.ru/sez-6/"> 6 СЕЗОН</a></li>
                    </ul>
                </h2>
                </h1>
                <hr>
            </div>

            <div>
              <h2>
                Мультсериал «Рик и Морти» — праздник для поклонников нестандартного юмора
              </h2> 
              <p style="color:#4035bd; width: 50%; border: 5px solid red">
                <b>Семья Бет и Джерри Смит</b> соответствует <del>типичным</del> <ins>нетепичным</ins> американским <s>традициям</s>.Они воспитывают 2 детей:
                17-летнюю дочку Саммер и 14-летнего сына Морти. Однако их жизнь сложно назвать размеренной из-за
                присутствия дедушки. Престарелый учёный Рик Санчез талантлив, обладает богатым воображением, всегда
                готов к авантюрам, но имеет проблемы с алкоголем и страдает постоянной отрыжкой. Он умеет собирать
                роботов, а благодаря летающей машине времени, созданной из хлама, может посещать другие измерения, прошлое и будущее.
                Открытия Санчеза и его фантастические путешествия не всегда безобидные. Порой они приводят к межгалактическим войнам и даже к гибели
                планет, но циничного учёного совсем не смущает сопутствующий ущерб. К неудовольствию зятя, мечтающего определить неистощимого на выдумки
                пожилого мужчину в дом престарелых, Рик использует собственного внука Морти в качестве спутника и прикрытия не слишком законных затей.
                Неуверенный в себе подросток без особенного энтузиазма участвует в приключениях, хотя они позволяют ему прогуливать школу.
                Тандем попадает в множество запутанных ситуаций, и уцелеть в них очень непросто. В далёких галактиках им приходится сталкиваться с неведомыми
                существами и подвергаться смертельной опасности, в основном по вине безответственного дедушки.  
                Изначально сумасбродные герои появились в анимационной пародии Джастина Ройланда на популярный фантастический фильм "Назад в будущее", а благодаря интересу
                к проекту уже к декабрю 2013 году американские зрители увидели первый сезон мультсериала. Его создали на программном блоке Adult Swim (дословный перевод "купание для взрослых")
                телеканала Cartoon Network. Из-за специфических шуток установлен достаточно высокий возрастной ценз (по данным портала Кинопоиск 18+). В мае 2018 года было
                объявлено о том, что планируется выпустить ещё как минимум 70 эпизодов. Беспринципный учёный и робкий подросток, достигший к 3-му сезону 15-летия, продолжают
                завоёвывать сердца зрителей.
              </p>
            </div>
        </main>
    </body>
</html>